// Training corpus generator.
//
// Every example carries the id of the template that produced it. The trainer
// splits on THAT id, never on the row, so the held-out set contains phrasings
// the model has genuinely never seen. Splitting by row would let near-identical
// siblings sit on both sides and would report a score that means nothing.

const pick = (a, r) => a[Math.floor(r() * a.length)];
function rng(seed) { let s = seed >>> 0; return () => (s = (s * 1664525 + 1013904223) >>> 0) / 4294967296; }

const BRAND = ['Amazon','Apple','Netflix','PayPal','Costco','Walmart','Chase','Wells Fargo','Bank of America','HSBC','Barclays','Halifax','Lloyds','USPS','FedEx','UPS','DHL','Royal Mail','Evri','Spotify','Hulu','Disney+','Microsoft','Google'];
const CARRIER = ['USPS','FedEx','UPS','DHL','Royal Mail','Evri','An Post','Canada Post'];
const BANK = ['Chase','Wells Fargo','Bank of America','Citi','HSBC','Barclays','Halifax','Lloyds','NatWest','Santander','TSB','Monzo'];
const NAME = ['Sarah','Michael','Emma','David','Jessica','Tom','Rachel','Daniel','Laura','James','Priya','Aisha','Marco','Chen','Olu','Ben','Katie','Nina'];
const REL = ['son','daughter','grandson','granddaughter','nephew','niece'];
const PARENT = ['mum','mom','dad','grandma','grandpa','nan','nana'];
const AMT = ['$50','$200','$450','$1,200','£75','£250','£1,800','€300','$2,000','$85.99','£19.99'];
const TLD = ['.xyz','.top','.icu','.info','.online','.click','.buzz','.co','.link','.shop'];
const SHORT = ['bit.ly/3xK2p','tinyurl.com/y7mq','cutt.ly/aW2x','t.co/9Kdm2','is.gd/pQ4z'];
const CODE = ['482913','749201','305827','916402','238471'];
const PHONE = ['888-555-0142','1-800-555-0199','(628) 555-0117','0800 555 0142','+1 855 555 0123'];
const URG = ['immediately','within 24 hours','today','right away','before midnight','urgently'];

// ---- SCAM templates -------------------------------------------------------
const SCAM = [
  ['gift', r => `${pick(BRAND,r)} support: your account is on hold. Settle with a ${pick(['iTunes','Google Play','Steam','Vanilla','Amazon'],r)} gift card ${pick(URG,r)} and send us the code.`],
  ['gift2', r => `To release your refund you must first purchase a ${pick(['Google Play','iTunes'],r)} card for ${pick(AMT,r)} and read me the numbers on the back.`],
  ['fam-jail', r => `${pick(['Grandma','Grandpa','Nan'],r)} it's me your ${pick(REL,r)}. I've been in an accident and I'm in jail. I need ${pick(AMT,r)} for bail. Please don't tell ${pick(['mom','dad','anyone'],r)}.`],
  ['fam-newnum', r => `Hi ${pick(PARENT,r)}, my phone ${pick(['broke','got smashed','died'],r)} so this is my new number. Can you ${pick(['help me pay','transfer','send'],r)} ${pick(AMT,r)} ${pick(URG,r)}? I'll pay you back.`],
  ['fam-newnum2', r => `Hello ${pick(PARENT,r)} 👋 lost my phone, using a temporary number. Are you free? I need a favour with a bill.`],
  ['pkg-fee', r => `${pick(CARRIER,r)}: your parcel is held at our depot pending a ${pick(['$1.95','£1.45','$2.99'],r)} customs fee. Confirm here: ${pick(['redeliver','parcel-fix','track-update'],r)}${pick(TLD,r)}/pay`],
  ['pkg-addr', r => `${pick(CARRIER,r)}: we could not deliver your package due to an incomplete address. Update it ${pick(URG,r)}: ${pick(SHORT,r)}`],
  ['toll', r => `${pick(['E-ZPass','FasTrak','SunPass','Dartford Crossing'],r)}: you have an unpaid toll balance of ${pick(['$6.99','$12.40','£4.20'],r)}. Pay now to avoid a violation fee: tolls-pay${pick(TLD,r)}`],
  ['bank-alert', r => `${pick(BANK,r)} ALERT: did you authorize a ${pick(AMT,r)} transaction? Reply NO if this wasn't you.`],
  ['safe-acct', r => `This is the ${pick(BANK,r)} fraud department. Your account is compromised. We need to move your money to a safe account ${pick(URG,r)} to protect it. Do not discuss this with anyone.`],
  ['otp', r => `${pick(BRAND,r)} security: we just sent a 6 digit code to your phone. Reply with that code to verify your identity and unlock your account.`],
  ['otp2', r => `Please read me the verification code we sent you so I can confirm I'm speaking to the account holder.`],
  ['prize', r => `Congratulations! You have been selected to receive a ${pick(AMT,r)} ${pick(BRAND,r)} gift card. Claim within 24 hours: ${pick(SHORT,r)}`],
  ['lottery', r => `WINNER! Your number was drawn in the ${pick(['national','international','holiday'],r)} lottery. To release your ${pick(AMT,r)} prize, pay the processing fee first.`],
  ['tech', r => `${pick(['Microsoft','Apple','Windows'],r)} Security: your computer has been infected and is sending virus signals. Call ${pick(PHONE,r)} ${pick(URG,r)} or install AnyDesk so we can fix it.`],
  ['gov', r => `IRS FINAL NOTICE: an arrest warrant has been issued for unpaid taxes. Call ${pick(PHONE,r)} ${pick(URG,r)} to settle. Do not ignore this message.`],
  ['gov2', r => `Social Security Administration: your number has been suspended due to suspicious activity. Call ${pick(PHONE,r)} to reactivate.`],
  ['romance', r => `My dearest, I feel destiny brought us together. I have never felt this way. Can we talk on ${pick(['WhatsApp','Telegram'],r)}? My heart is yours.`],
  ['pig', r => `I made ${pick(AMT,r)} last week on a trading platform my uncle showed me. Guaranteed returns in crypto. I can teach you if you're interested.`],
  ['job', r => `Work from home opportunity: earn ${pick(['$300','$450','£280'],r)} a day, no experience needed. Apply on Telegram @hr${Math.floor(r()*900+100)}`],
  ['sextort', r => `I have recorded a video of you through your webcam. Send ${pick(AMT,r)} in bitcoin within 48 hours or I send it to your contacts.`],
  ['advfee', r => `Dear friend, I am a ${pick(['widow','widower','barrister','bank official','trustee','fund manager'],r)} holding ${pick(['$4.5 million','$12 million','£8 million'],r)} in an unclaimed account. I need your help transferring it and will share 30%.`],
  ['advfee2', r => `Greetings. I am contacting you regarding an unclaimed estate of ${pick(['$6 million','£3.2 million'],r)}. As next of kin you may claim it once the release fee is settled.`],
  ['overpay', r => `I've sent you too much for the item by mistake. Please deposit the check and wire back the difference of ${pick(AMT,r)}.`],
  ['charity', r => `Urgent ${pick(['hurricane','earthquake','flood'],r)} relief appeal. Donate today by ${pick(['gift card','wire transfer','bitcoin','Zelle'],r)} to help families.`],
  ['sub', r => `${pick(['Netflix','Spotify','Disney+','Hulu'],r)}: your payment failed and your account will be suspended. Update your card here: ${pick(['billing','renew','account'],r)}-verify${pick(TLD,r)}`],
  ['callback', r => `${pick(BRAND,r)}: your order for ${pick(AMT,r)} has shipped. If this wasn't you call ${pick(PHONE,r)} ${pick(URG,r)}.`],
  ['qr', r => `Scan the QR code below to claim your ${pick(AMT,r)} refund. Offer expires ${pick(['today','tonight'],r)}.`],
  ['pet', r => `The ${pick(['puppy','kitten','teacup poodle'],r)} is still available. Send a ${pick(AMT,r)} deposit to hold her and we'll arrange shipping.`],
  ['recovery', r => `Our funds recovery department can get back the money you lost to fraud. A small retainer of ${pick(AMT,r)} is required to open your case.`],
  ['remote', r => `To resolve the issue please install ${pick(['AnyDesk','TeamViewer','UltraViewer'],r)} and give us the access code on your screen.`],
  ['wrongnum', r => `Hi is this ${pick(NAME,r)}? Sorry, wrong number! But you seem nice, where are you from? I'm new here and looking to make friends.`],
  ['hop', r => `Message me on ${pick(['WhatsApp','Telegram','Signal'],r)} to continue, this app is not secure for our conversation.`],
  ['phish-login', r => `${pick(BRAND,r)}: unusual sign-in detected from a new device. Verify your account ${pick(URG,r)} or it will be locked: ${pick(['secure','verify','login'],r)}-${pick(['acct','id'],r)}${pick(TLD,r)}`],
  ['crypto-wallet', r => `Your wallet has been flagged. Confirm your recovery phrase to restore access to your funds.`],
  ['stay-line', r => `This is the security team at your ${pick(['bank','building society','credit union'],r)}. There has been activity on your ${pick(['savings','current account'],r)} we must walk you through. Please stay on the line and do not hang up.`],
  ['fake-debt', r => `Final reminder regarding the outstanding balance on your account. Failure to respond ${pick(['today','within 24 hours'],r)} may result in further action being taken.`],
  ['borrowed', r => `${pick(['Dad','Mum'],r)} it's me, I dropped my phone down the toilet. I'm on a mate's phone. Are you about? I need a hand with something.`],
  ['warranty', r => `We have been trying to reach you about your vehicle's extended warranty before it ${pick(['expires','lapses'],r)}. Press 1 to speak with a specialist.`],
  ['vague-favour', r => `Morning! Quick favour — I'm ${pick(['stuck in a meeting','in a hospital appointment','abroad'],r)} and can't talk. Could you sort something for me? Let me know when you're free.`],
  ['friend-invest', r => `Hey! Long time. I've been doing really well with a platform a ${pick(['friend','colleague'],r)} put me onto — ${pick(['doubled','tripled'],r)} what I put in. Happy to walk you through it.`],
  ['sub-lapsed', r => `We noticed your ${pick(['subscription','storage plan','licence'],r)} lapsed. To keep your ${pick(['files','photos','account'],r)}, settle the small outstanding amount at the link below.`],
  ['compliance', r => `I'm reaching out from the ${pick(['compliance','audit','risk'],r)} office regarding an irregularity on your file. Please confirm your details so we can close this matter quietly.`],
  ['av-expired', r => `Your antivirus expired ${pick(['3 days','a week'],r)} ago and we have detected unusual activity. Ring our helpline and we will guide you through removing it.`],
  ['authority-secret', r => `${pick(['Ms Chen','Mr Patel','Officer Hall'],r)} from the ${pick(['Inland Revenue','council tax office','tax office'],r)} here. Our records show a ${pick(['discrepancy','underpayment'],r)} on your file. I would advise you not to discuss this while the investigation is open.`],
  ['helpdesk', r => `Hello, this is the ${pick(['technical department','helpdesk','support team'],r)}. We are seeing your ${pick(['router','machine','computer'],r)} behaving unusually. If you can get to a computer I will walk you through securing it.`],
  ['deliv-nofee', r => `Delivery attempted. Reschedule required. A ${pick(['handling','storage','release'],r)} amount of ${pick(['1.79','2.99','3.49'],r)} is outstanding before the item can be released.`],
  ['detail-harvest', r => `Calling from the ${pick(['card protection','fraud prevention','security'],r)} team. To confirm I am speaking to the right person, could you read me the ${pick(['three digits on the back','long number on your card','date of birth'],r)}?`],
  ['pension-audit', r => `We are conducting a routine audit of ${pick(['pension','savings','policy'],r)} holdings. To confirm your entitlement please provide your policy number and date of birth.`],
  ['refund-harvest', r => `You have been overcharged on your ${pick(['energy','water','broadband'],r)} bill. To process your refund we need your account number and sort code.`],
  ['love-phone', r => `Hi ${pick(['love','darling'],r)}, it's me. Phone's playing up so using this one. Are you free? Bit of a situation and I didn't want to worry you.`],
  ['cover-lapse', r => `Our records indicate your ${pick(['warranty coverage','policy','cover'],r)} has lapsed. Press one now to be connected with a ${pick(['coverage','renewals'],r)} specialist.`],
  ['school-emerg', r => `URGENT: your ${pick(['child','grandchild'],r)} has been involved in an incident at school. Call this number immediately for details.`],
  ['solicitor', r => `I represent your ${pick(['grandson','nephew'],r)} in a legal matter. He has asked that his ${pick(['mother','parents'],r)} not be told while bail is arranged.`],
  ['courier-over', r => `I saw your listing and would like to buy it. My courier will collect. I will send extra to cover his fee — just forward that part on to him.`],
  ['es-nocuelgue', r => `Buenos dias, hay un problema con su cuenta. No cuelgue y confirme su numero de tarjeta ahora mismo.`],
  ['breach-comp', r => `Following the recent data breach you are entitled to compensation. Confirm your identity and bank details to receive your payment.`],
  ['neighbour-ask', r => `Hi, sorry to bother — it's me from number ${Math.floor(r()*40+1)}. Had a bit of an emergency and I'm short. Could you help and I'll drop it back tomorrow?`],
  ['borrow-ask', r => `Hiya, it's ${pick(NAME,r)}. Bit stuck this week — any chance you could lend me ${pick(AMT,r)} till payday? I'll pay you straight back.`],
  ['dormant', r => `Dormant account notice: sign in via the link provided to prevent permanent closure of your ${pick(['savings','account'],r)}.`],
  ['press-lock', r => `Automated security notice. Irregular sign-in detected. Press 1 immediately to lock your account.`],
  ['courier-fee', r => `I'd like to purchase the item. My shipping agent will collect — I'll add his fee to the payment, please pass that part on to him.`],
  ['unfam-phone', r => `It's me ${pick(['darling','love'],r)}, different phone, mine's in for repair. Are you around? Something's come up and I can't ring.`],
  ['purse', r => `Hiya, it's ${pick(["next door's daughter","your neighbour"],r)}. Mum's had a fall and I've had to rush out without my purse. Any chance you could help?`],
  ['school-inc', r => `This is the school office. There has been an incident involving your ${pick(['grandchild','grandson','granddaughter'],r)}. Please ring back on this number urgently.`],
  ['de-bank', r => `Guten Tag, Ihr Konto wird heute gesperrt. Bitte bestatigen Sie sofort Ihre Daten.`],
  ['de-paket', r => `Ihr Paket wird zurueckgehalten. Eine Gebuehr von ${pick(['1,99','2,50'],r)} Euro ist faellig.`],
  ['pension-cold', r => `Good morning, I'm calling from the ${pick(['pensions advisory service','retirement review team'],r)}. There is an issue with your entitlement we must sort out before the deadline passes.`],
  ['storage-full', r => `Notification: your cloud storage is full and your photos will be deleted in 48 hours unless you upgrade using the secure form.`],
  ['accident-claim', r => `Hello, we are calling about the accident you had that wasn't your fault. We can start your claim today, I just need a few details.`],
  ['loan-fee', r => `You have been pre-approved for a loan of ${pick(['5,000','8,000'],r)} at a fixed rate. To release the funds we require the arrangement fee up front.`],
  ['licence-renew', r => `Your ${pick(['TV licence','vehicle tax','permit'],r)} could not be renewed as the details we hold are out of date. Update them now to avoid a penalty.`],
  ['forex-intro', r => `Hi! Sorry to message out of the blue, I got your number from the group. I have been trading ${pick(['forex','commodities'],r)} and thought of you.`],
  ['deposit-hold', r => `The item is reserved for you but we need a deposit today to hold it, otherwise it goes to the next person on the list.`],
  ['debt-enforce', r => `This is a final notice from the debt recovery team regarding monies owed. Contact us today to avoid enforcement.`],
  ['sys-upgrade', r => `We are upgrading our systems. To keep your account active please re-register your card details through the link below.`],
  ['licence-key', r => `Hello, your computer's licence key has expired. Ring this number and a technician will renew it for you remotely.`],
  ['foreign-charge', r => `Attention: a payment of ${pick(['749.00','1,204.00'],r)} to a foreign merchant is pending on your card. If you did not make this, call us on the number below.`],
  ['missold', r => `I have been asked to contact you about compensation owed for mis-sold ${pick(['insurance','pension'],r)}. There is a small processing fee to release it.`],
  ['booking-declined', r => `Your booking could not be confirmed as the card was declined. Re-enter your details within the hour or the room will be released.`],
  ['password-ask', r => `Security alert: someone in another country is trying to access your account. Confirm your password to stop them.`],
  ['rx-fee', r => `We tried to deliver your prescription but nobody was in. A small redelivery charge is payable before we can try again.`],
  ['police-fine', r => `It's your grandson. I'm at the police station and they will only release me if the fine is paid today. Please don't tell mum.`],
  ['landlord', r => `${pick(['Mum','Dad'],r)}, the landlord is threatening to change the locks. I know it's a lot to ask but could you help me out until my wages land?`],
  ['fr-colis-fee', r => `Bonjour, un colis vous attend. Des frais de livraison de 2,30 euros restent a regler avant expedition.`],
  ['courier-card', r => `This is your bank's security team. We are sending a courier to collect your card for safe destruction. Please cut it in half and hand it over.`],
  ['ticket-resale', r => `I have two tickets for ${pick(['Saturday','the final'],r)} going cheap as I can't make it. Bank transfer only I'm afraid, first come first served.`],
  ['fake-recruit', r => `Congratulations on the role! Before we finalise, please send a scan of your passport and your bank details for payroll.`],
  ['green-grant', r => `We noticed your property qualifies for a government ${pick(['green','insulation','solar'],r)} grant. The surveyor is in your area today and the discount ends tonight.`],
  ['medic-alert', r => `Your relative has arranged a medical alert pendant for you. We just need to confirm the monthly payment details to activate it.`],
  ['rental-dep', r => `The ${pick(['flat','house'],r)} is still available. To secure the viewing slot please transfer the holding deposit today, plenty of interest on this one.`],
  ['utility-access', r => `This is the water board. We need access to check contamination in your area. Our operative will call round shortly.`],
  ['simswap', r => `Alert: a SIM swap request was made on your number. If this wasn't you, reply STOP and confirm the last four digits of your account.`],
  ['carehome', r => `Your ${pick(['father','mother'],r)}'s care home fees are overdue and ${pick(['his','her'],r)} place is at risk. Payment must be made today to avoid discharge.`],
  ['phone-donate', r => `We're collecting for the local children's hospice. Card payment over the phone is easiest, or a bank transfer if you prefer.`],
  ['benefit-over', r => `You were overpaid benefits three years ago. The sum must be repaid this week or it will be passed to enforcement.`],
  ['trial-trap', r => `Free trial ends tonight. If you don't want to be charged ${pick(['89.99','49.99'],r)} monthly, confirm your card so we can cancel it.`],
  ['invoice-swap', r => `I'm the new bookkeeper. The supplier bank details have changed, please use the new account for the invoice due today.`],
  ['voice-clone', r => `Voice message from your ${pick(['son','daughter'],r)}. They sound distressed and mention an accident. Press 1 to hear the full message.`],
  ['car-dep', r => `The vehicle is exactly as described. I'll hold it for you with a ${pick(['500','300'],r)} deposit, my brother handles the paperwork.`],
  ['petins', r => `Your pet insurance lapsed last month. Reconfirm your card now or the policy cannot be reinstated.`],
  ['roofer', r => `We are the roofing team who did next door. We noticed slipped tiles on yours, we can sort it now for cash.`],
  ['meter-check', r => `Your energy meter needs an urgent safety check. Confirm your account number and we'll book the engineer.`],
  ['es-tecnico', r => `Buenas tardes, somos del servicio tecnico. Su linea sera cortada hoy si no confirma sus datos bancarios.`],
  ['police-courier', r => `This is the police. Your card is being used by staff at your branch. Don't tell them — withdraw the cash and we'll collect it as evidence.`],
  ['bank-courier', r => `For your safety we are sending an officer to collect your card. Please cut it in half and hand it over when they arrive.`],
  ['app-update', r => `Your banking app must be updated to meet new regulations. Install the update from the link to keep access.`],
  ['reimburse', r => `Our driver couldn't reach you so your neighbour paid the customs charge. Please reimburse them via the link.`],
  ['pay-to-work', r => `Position confirmed pending certification. The training module costs ${pick(['149','199'],r)} and is refunded with your first pay packet.`],
  ['rebate-harvest', r => `Council tax rebate approved for your band. Provide your account details and we'll process the refund today.`],
  ['cash-collect', r => `We collect clothing for the children's charity. Leave bags out Thursday, and any cash donations in the envelope provided.`],
  ['syndicate', r => `Our syndicate has won on 9 of the last 12 draws. A one-off buy-in secures your share of the next jackpot.`],
  ['timeshare', r => `Our legal team can release you from your timeshare obligations. The court application fee is payable before we can lodge it.`],
  ['bailiff', r => `Enforcement agent attending your address tomorrow regarding an unpaid liability. Settle now to prevent removal of goods.`],
  ['pension-lib', r => `You can access your pension before 55 through a legitimate loophole. Transfer to our scheme and we handle the paperwork.`],
  ['romance-customs', r => `My darling, I'm being held at customs over the gift I sent you. They want a clearance charge and my cards are frozen here.`],
  ['boss-gift', r => `It's the boss. I'm in back-to-back meetings. Need you to buy gift cards for the client thank-yous and send me the codes.`],
  ['school-pay', r => `School trip payment failed. Please re-send via bank transfer today or your grandchild's place will be given away.`],
  ['switch-cold', r => `You're paying too much for energy. I can switch you now over the phone, I just need your meter number and bank details.`],
  ['parking', r => `Unpaid parking charge notice. The amount doubles at midnight. Pay now to avoid court action.`],
  ['supp-trap', r => `Your trial of the joint supplement is ending. We'll continue the monthly shipment at ${pick(['79.99','59.99'],r)} unless you call to confirm cancellation.`],
  ['prize-fee', r => `You've been entered into the grand prize draw. A small entry confirmation fee applies before the draw closes.`],
  ['broadband-cut', r => `Your broadband will be disconnected within the hour for non-payment. Press 1 now to settle by card.`],
  ['de-paket2', r => `Ihr Paket konnte nicht zugestellt werden. Zahlen Sie die Gebuehr von 2,99 Euro ueber den Link.`],
  ['hmrc-app', r => `HMRC: you are due a tax refund of ${pick(['284.60','412.30'],r)}. Download our app and sign in to claim it before the deadline.`],
  ['landlord-abroad', r => `I'm the landlord but I'm working abroad at the moment. Send the first month and I'll post the keys out to you.`],
  ['virus-popup', r => `WARNING: your device is infected with 3 viruses. Do not restart. Call our certified technicians on the number shown.`],
  ['group-admin', r => `Hi, I'm the new admin for the family group. Verify your number by sending me the six digit code you'll receive.`],
  ['sponsor', r => `Sponsor me for the marathon! Just transfer to my personal account and I'll pass it all to the charity.`],
  ['bond-invest', r => `Green energy bonds paying 8.4% fixed, capital protected, FSCS covered. Limited allocation remaining this quarter.`],
  ['ins-beat', r => `We can beat your current insurance quote by 40%. I just need your policy number and card to secure the price today.`],
  ['solar-service', r => `Your solar panels are due their compulsory five year service. Failure to book invalidates your warranty.`],
  ['grant-survey', r => `The council is surveying homes for the insulation grant. Confirm ownership and your date of birth and we'll book you in.`],
  ['advance-loan', r => `Short term advance approved, no credit check. The security deposit is returned with your first repayment.`],
  ['acct-lagos', r => `Your account was accessed from a device in ${pick(['Lagos','Moscow'],r)}. If this wasn't you, verify your identity on the link now.`],
  ['copyright', r => `Copyright infringement detected on your account. Pay the settlement fee within 72 hours or legal proceedings begin.`],
  ['nhs-fee', r => `Your NHS appointment requires a booking fee of ${pick(['12.50','9.99'],r)} to be confirmed. Pay online to keep your slot.`],
  ['funeral-plan', r => `Have you considered a prepaid funeral plan? We can lock today's price if you set up the direct debit on this call.`],
  ['will-rewrite', r => `Your will is not legally valid under the new rules. Our specialist can rewrite it, the fee is payable up front.`],
  ['equity-release', r => `You could release ${pick(['60,000','45,000'],r)} tax free from your home. No repayments ever. Reply YES for a callback.`],
  ['drains', r => `We were working on the drains next door and noticed yours are collapsing. We can excavate today, cash price.`],
  ['double-refund', r => `Our error: we refunded you twice. Please return the duplicate ${pick(['480','320'],r)} by bank transfer to the account below.`],
  ['coin-giveaway', r => `${pick(['Elon','The exchange'],r)} is doubling every coin sent to the giveaway address for the next hour. Send 0.1 and receive 0.2 back.`],
  ['fr-facture', r => `Votre facture est impayee. Reglez sous 24 heures ou votre ligne sera suspendue.`],
  ['es-bank', r => `${pick(['BBVA','Santander','Banamex'],r)}: su cuenta sera suspendida hoy. Verifique su informacion inmediatamente aqui: acceso-seguro${pick(TLD,r)}`],
  ['es-pkg', r => `Su paquete esta retenido en aduana. Pague la tarifa de ${pick(['$2.50','$1.99'],r)} aqui: correos-entrega${pick(TLD,r)}`],
  ['es-prize', r => `Felicidades! Ha ganado un premio de la loteria. Reclame su premio hoy mismo antes de que expire.`],
  ['fr-bank', r => `${pick(['BNP','Societe Generale'],r)}: votre compte sera bloque. Verifiez votre identite immediatement, cliquez ici: verif-compte${pick(TLD,r)}`],
  ['fr-pkg', r => `Votre colis est retenu, des frais de douane de ${pick(['1,95€','2,50€'],r)} sont requis. Payez ici: colis-suivi${pick(TLD,r)}`],
  ['pt-bank', r => `${pick(['Itau','Bradesco'],r)}: sua conta sera suspensa. Verifique sua identidade agora: acesso-seguro${pick(TLD,r)}`],
];

// ---- LEGIT templates ------------------------------------------------------
// Deliberately includes the hard cases: real codes, real delivery notices, real
// bank alerts, real promotions. If the model cannot pass these it is useless.
const LEGIT = [
  ['fam-chat', r => `Hi ${pick(PARENT,r)}, running about ${pick(['10','20','30'],r)} minutes late. See you soon x`],
  ['fam-chat2', r => `${pick(NAME,r)} says thank you for the birthday card, she loved it!`],
  ['fam-chat3', r => `Can you pick up milk and bread on your way home? Thanks!`],
  ['fam-chat4', r => `Just landed safely. Battery nearly dead, will ring you tomorrow.`],
  ['fam-chat5', r => `Happy birthday ${pick(['Grandad','Grandma','Dad','Mum'],r)}! Hope you have a lovely day. Love from all of us.`],
  ['fam-newnum-ok', r => `Hi ${pick(PARENT,r)}, got a new number after switching networks. Save it when you get a sec. Nothing urgent!`],
  ['appt', r => `Reminder: your appointment with Dr. ${pick(NAME,r)} is on ${pick(['Tuesday','Thursday','Monday'],r)} at ${pick(['9:15','11:30','3:45'],r)}. Reply CANCEL to cancel.`],
  ['appt2', r => `Your ${pick(['dental','optician','physio'],r)} appointment is confirmed for ${pick(['tomorrow','Friday'],r)}. Please arrive 10 minutes early.`],
  ['rx', r => `Your prescription is ready for collection at ${pick(['Boots','Walgreens','CVS','the pharmacy'],r)} High Street.`],
  ['delivery-ok', r => `${pick(CARRIER,r)}: your parcel was delivered and left with a neighbour at number ${Math.floor(r()*40+1)}.`],
  ['delivery-ok2', r => `${pick(BRAND,r)}: your order has shipped and is arriving ${pick(['today','tomorrow'],r)}. Track it in the app. No action needed.`],
  ['delivery-ok3', r => `Your ${pick(CARRIER,r)} delivery is out for delivery and will arrive between ${pick(['9am and 12pm','1pm and 5pm'],r)}.`],
  ['otp-real', r => `Your ${pick(BRAND,r)} verification code is ${pick(CODE,r)}. Do not share this code with anyone.`],
  ['otp-real2', r => `${pick(CODE,r)} is your one-time login code. It expires in 10 minutes. We will never ask you for it.`],
  ['bank-real', r => `${pick(BANK,r)}: a payment of ${pick(AMT,r)} to ${pick(['Tesco','Sainsburys','Target','Costco'],r)} was authorised on your card ending ${Math.floor(r()*9000+1000)}.`],
  ['bank-real2', r => `${pick(BANK,r)}: your statement for ${pick(['March','April','May'],r)} is ready to view in the app. We will never ask for your PIN or password.`],
  ['bank-real3', r => `Your direct debit of ${pick(AMT,r)} to ${pick(['British Gas','EDF','Thames Water'],r)} will be taken on the 1st.`],
  ['receipt', r => `Thanks for your payment of ${pick(AMT,r)}. Your receipt is available in your account.`],
  ['restaurant', r => `Your table for ${pick(['2','4','6'],r)} at ${pick(['7pm','8:30pm'],r)} on ${pick(['Friday','Saturday'],r)} is confirmed. See you then!`],
  ['uber', r => `Your ride is arriving now. ${pick(['Toyota Prius','VW Golf','Nissan Leaf'],r)}, licence ${pick(['FX21 KLM','LM19 TRD','8XKD224'],r)}.`],
  ['council', r => `Council tax: your ${pick(['April','May'],r)} statement is now available in your online account.`],
  ['bins', r => `Reminder: bin collection moves to ${pick(['Wednesday','Thursday'],r)} this week due to the bank holiday.`],
  ['school', r => `${pick(['Parents evening','Sports day','The school trip'],r)} is on ${pick(['Thursday','Monday'],r)}. Please return the form by Friday.`],
  ['work', r => `The ${pick(['standup','review','1:1'],r)} has moved to ${pick(['2pm','10:30'],r)}. Calendar updated.`],
  ['promo-real', r => `${pick(BRAND,r)}: 20% off this weekend in store and online. Reply STOP to opt out.`],
  ['promo-real2', r => `Your ${pick(['Tesco Clubcard','Nectar','loyalty'],r)} points statement is ready. You have ${Math.floor(r()*900+100)} points.`],
  ['travel', r => `Your flight ${pick(['BA','AA','UA'],r)}${Math.floor(r()*900+100)} is on time. Boarding at gate ${pick(['12','7','23'],r)} at ${pick(['14:20','09:05'],r)}.`],
  ['travel2', r => `Check-in is now open for your flight on ${pick(['Tuesday','Saturday'],r)}. Check in via the app.`],
  ['utility', r => `Your ${pick(['electricity','gas','water'],r)} meter reading is due. Submit it online or reply with the reading.`],
  ['vet', r => `${pick(['Bella','Max','Luna'],r)} is due for her vaccination. Call us to book a time that suits you.`],
  ['community', r => `The ${pick(['walking group','book club','coffee morning'],r)} meets ${pick(['Tuesday','Thursday'],r)} at 10. All welcome!`],
  ['neighbour', r => `Took in a parcel for you this morning, pop round whenever. ${pick(NAME,r)} at number ${Math.floor(r()*40+1)}.`],
  ['charity-real', r => `Thank you for your donation. Your support helps us reach more families this winter.`],
  ['insurance', r => `Your policy renews on the ${Math.floor(r()*28+1)}. No action is needed, it will renew automatically.`],
  ['libr', r => `Your library book is due back on ${pick(['Friday','the 14th'],r)}. Renew online if you need longer.`],
  // ---- hard negatives -----------------------------------------------------
  // Real messages that share almost all their vocabulary with a scam. These are
  // the ones that matter: without enough of them the model learns that any
  // mention of a code, a parcel or a bank is a scam, and starts flagging the
  // genuine article. One thin OTP template was enough to force the decision
  // threshold to 0.965 and crush recall.
  ['otp-r1', r => `Your ${pick(BRAND,r)} verification code is ${pick(CODE,r)}. Do not share it with anyone.`],
  ['otp-r2', r => `${pick(CODE,r)} is your one-time login code. It expires in 10 minutes.`],
  ['otp-r3', r => `Your security code is ${pick(CODE,r)}. ${pick(BRAND,r)} will never ask you for this code.`],
  ['otp-r4', r => `Use ${pick(CODE,r)} to complete your sign-in. If you did not request this, ignore this message.`],
  ['otp-r5', r => `${pick(BANK,r)}: your authorisation code for the payment is ${pick(CODE,r)}. Never share this with anyone, including our staff.`],
  ['otp-r6', r => `Verification code: ${pick(CODE,r)}. Enter it in the app to finish setting up your account.`],
  ['pkg-r1', r => `${pick(CARRIER,r)}: your parcel ${pick(['is on its way','has left our depot','is with the driver'],r)} and will arrive ${pick(['today','tomorrow','Thursday'],r)}. No action needed.`],
  ['pkg-r2', r => `${pick(CARRIER,r)}: we tried to deliver but you were out. We'll try again ${pick(['tomorrow','Monday'],r)} — no fee required.`],
  ['pkg-r3', r => `Your ${pick(BRAND,r)} order ${pick(['#','no. '],r)}${Math.floor(r()*900000+100000)} has been dispatched. Track it in your account.`],
  ['bank-r1', r => `${pick(BANK,r)}: we've spotted an unusual transaction of ${pick(AMT,r)}. If this was you, no action is needed. If not, call the number on the back of your card.`],
  ['bank-r2', r => `${pick(BANK,r)}: your balance is low (${pick(['£12.40','$18.20','£4.05'],r)}). Top up to avoid charges. We will never text you a link to log in.`],
  ['bank-r3', r => `${pick(BANK,r)}: your new card is on its way and should arrive within 5 working days.`],
  ['bank-r4', r => `${pick(BANK,r)} fraud team: we have blocked a suspicious payment and cancelled your card. Please call us using the number on your card.`],
  ['prize-r1', r => `Thanks for entering the ${pick(['village fete','school','club'],r)} raffle! Tickets will be drawn on ${pick(['Saturday','the 14th'],r)}.`],
  ['prize-r2', r => `You came second in the ${pick(['quiz','bake off','photo competition'],r)}! Pop in to collect your certificate whenever suits.`],
  ['urgent-r1', r => `URGENT: ${pick(NAME,r)} has been taken to ${pick(['the hospital','A&E'],r)}. Please call me when you can — it's ${pick(NAME,r)}.`],
  ['urgent-r2', r => `Please respond today if you can — we need numbers for the ${pick(['booking','minibus','catering'],r)} by tonight.`],
  ['acct-r1', r => `Your ${pick(BRAND,r)} subscription renews on the ${Math.floor(r()*28+1)} at ${pick(AMT,r)}. Manage it in the app.`],
  ['acct-r2', r => `Password changed successfully. If this wasn't you, open the app and change it again.`],
  ['gov-r1', r => `HMRC: your tax return is due by 31 January. File online at gov.uk. We will never ask for payment by text.`],
  ['gov-r2', r => `Your ${pick(['passport','driving licence'],r)} application has been received and is being processed.`],
  ['pay-r1', r => `${pick(NAME,r)} sent you ${pick(AMT,r)} — "${pick(['dinner','the tickets','taxi share'],r)}". It's in your account.`],
  ['pay-r2', r => `Your transfer of ${pick(AMT,r)} to ${pick(NAME,r)} was successful.`],
  ['favour-r', r => `Morning! Quick favour — could you ${pick(['feed the cat','water the plants','take the bins out'],r)} tomorrow? Key is in the usual place.`],
  ['surgery-r', r => `This is the surgery calling about your ${pick(['blood test','scan'],r)} results. Nothing to worry about, please ring us back when convenient.`],
  ['depot-r', r => `The driver couldn't find the property so your parcel is back at the depot. Collect any time this week, no charge.`],
  ['compliance-r', r => `Hi, it's the compliance team at work — could you re-sign the policy doc on the intranet when you get a minute? No rush.`],
  ['mot-r', r => `Your ${pick(['MOT','service','inspection'],r)} is due next month. Give us a ring to book a slot that suits you.`],
  ['catchup-r', r => `Hey! Long time. Fancy a coffee next week? Would be lovely to catch up properly.`],
  ['sub-r', r => `Your ${pick(['antivirus','cloud storage'],r)} subscription renews automatically on the ${Math.floor(r()*28+1)}. No action needed.`],
  ['kid-good', r => `${pick(['Dad','Mum'],r)} it's me — got the job!! Ring you tonight to tell you all about it xx`],
  ['reminder-r', r => `Final reminder: the ${pick(['village hall','club','committee'],r)} booking form needs returning by Friday please.`],
  ['debt-real', r => `Your ${pick(['gas','electricity','broadband'],r)} bill of ${pick(AMT,r)} is due on the ${Math.floor(r()*28+1)}. View the full breakdown in your account.`],
  // Non-English legitimate messages. Without enough of these the model learns
  // that Spanish or French is itself a scam signal — it scored a real note from
  // a daughter ("Hola mama, llego 15 minutos tarde") at 0.73 purely on language.
  // Scammers pick the victim's language, so the corpus must not treat the
  // language as the signal.
  ['authority-r', r => `${pick(['Ms Chen','Mr Patel'],r)} from the ${pick(['surgery','council','practice'],r)} here — just confirming your appointment on ${pick(['Tuesday','Thursday'],r)}. Nothing urgent.`],
  ['helpdesk-r', r => `Following up on the support ticket you raised — it is resolved, no action needed at your end.`],
  ['deliv-nofee-r', r => `We tried to deliver today but nobody was home, so it is in the porch as agreed. Nothing to pay.`],
  ['card-r', r => `Calling from the card team — your replacement card was posted yesterday and should arrive ${pick(['Thursday','Monday'],r)}.`],
  ['pension-r', r => `Your annual pension statement is now available to view in your online account.`],
  ['refund-r', r => `You were overcharged on last month's bill. We have already credited your account — nothing for you to do.`],
  ['love-r', r => `Running late from work ${pick(['love','darling'],r)}, don't wait for dinner. See you about eight x`],
  ['cover-r', r => `Your cover renews automatically on the ${Math.floor(r()*28+1)} at the same premium. Documents are in your account.`],
  ['school-r', r => `Message from the school office: ${pick(['sports day','parents evening'],r)} is moved to ${pick(['Thursday','Monday'],r)}. No action needed.`],
  ['solicitor-r', r => `I represent the estate and can confirm probate has completed. No action needed from you at this stage.`],
  ['buyer-r', r => `Is the ${pick(['bike','table','pram'],r)} still available? Could I collect ${pick(['Saturday','Sunday'],r)} morning and pay cash on the day?`],
  ['es-tienda', r => `Buenos dias, su pedido esta listo para recoger en la tienda. Muchas gracias!`],
  ['breach-r', r => `Following the outage last week we have applied a credit to your account. It will show on your next bill.`],
  ['neighbour-r', r => `Took in a parcel for you this morning — I'm at number ${Math.floor(r()*40+1)}, pop round any time this evening.`],
  ['borrow-r', r => `${pick(NAME,r)} here — are you still ok for ${pick(['Saturday','the quiz','coffee'],r)}? Let me know either way!`],
  // Bereavement in ordinary use. The advance-fee templates say "I am a widow
  // with $4.5 million"; without these the model learns that "widow" is the
  // signal, and flags a real widower introducing himself to a walking group.
  // A large share of this app's users are widowed, so that failure is not
  // hypothetical — it was scoring 0.70 and setting the whole threshold.
  ['widow-r1', r => `I am a ${pick(['widow','widower'],r)} and I'd like to join the ${pick(['Tuesday walking','Thursday coffee','book'],r)} group please.`],
  ['widow-r2', r => `Since my ${pick(['husband','wife'],r)} passed I've been getting out more. Is there space at the ${pick(['lunch club','choir','allotment'],r)}?`],
  ['widow-r3', r => `My late ${pick(['husband','wife'],r)} always spoke fondly of you. I'd love to catch up sometime if you're free.`],
  ['widow-r4', r => `Thank you for the flowers and the kind words at the funeral. It meant a great deal to me and the family.`],
  ['widow-r5', r => `The bereavement support group meets on ${pick(['Wednesdays','Mondays'],r)} at 2pm. Everyone is welcome, no need to book.`],
  ['widow-r6', r => `I lost my ${pick(['husband','wife'],r)} last year and I'm trying to get out a bit more. Does the ${pick(['club','group'],r)} still meet on ${pick(['Tuesdays','Fridays'],r)}?`],
  ['widow-r7', r => `As a ${pick(['widow','widower'],r)} I'm entitled to the single person discount. Could you tell me how to apply?`],
  ['widow-r8', r => `My ${pick(['husband','wife'],r)} passed away in ${pick(['March','the spring'],r)}. I'm sorting out the paperwork and wondered if you could advise.`],
  ['widow-r9', r => `Widowed neighbour here at number ${Math.floor(r()*40+1)} — thank you for clearing my path last week, it was very kind.`],
  ['deliv-r4', r => `Your ${pick(CARRIER,r)} delivery is out for delivery and will arrive between ${pick(['9am and 12pm','1pm and 5pm'],r)}.`],
  ['deliv-r5', r => `Your driver is 3 stops away. Track the van live in the app.`],
  ['deliv-r6', r => `Delivered — signed for by ${pick(NAME,r)} at ${pick(['10:42','14:15'],r)}. Thanks for shopping with us.`],
  ['deliv-r7', r => `Your ${pick(BRAND,r)} return has been received and your refund is on its way.`],
  ['deliv-r8', r => `Collection booked for ${pick(['Tuesday','Friday'],r)}. Just leave the parcel with a neighbour if you are out.`],
  ['pension-r2', r => `It's the pensions team — your annual statement has been posted and should reach you this week.`],
  ['storage-r', r => `Your cloud storage is nearly full. You can free up space or upgrade any time in settings — nothing will be deleted.`],
  ['service-r', r => `Calling to confirm your ${pick(['car','boiler'],r)} is booked in on ${pick(['Thursday','Tuesday'],r)}. Nothing needed from you before then.`],
  ['loan-r', r => `You've been pre-approved for a higher limit. There is no charge and no obligation — details are in your online account.`],
  ['licence-r2', r => `Your ${pick(['TV licence','vehicle tax'],r)} renews automatically next month. Your details are up to date, so there is nothing to do.`],
  ['group-r', r => `Hi! Sorry to message out of the blue — I got your number from the ${pick(['walking','book'],r)} group. Are you coming on ${pick(['Saturday','Tuesday'],r)}?`],
  ['reserve-r', r => `The item is reserved under your name until ${pick(['Friday','Monday'],r)}. No deposit needed, just come in when you can.`],
  ['library-r', r => `A reminder that two library books are overdue. No fine, just bring them back when you are passing.`],
  ['sys-r', r => `We are upgrading our systems on Sunday night. The app may be unavailable for a few hours — no action needed.`],
  ['licence-r3', r => `Your software licence renews automatically on the ${Math.floor(r()*28+1)}. The receipt will be emailed to you.`],
  ['charge-r', r => `A payment of ${pick(['749.00','82.40'],r)} to ${pick(['Wickes','Tesco','Argos'],r)} was authorised on your card ending ${Math.floor(r()*9000+1000)}. View it in the app.`],
  ['missold-r', r => `We have reviewed your insurance complaint and upheld it. Your compensation will be paid automatically, with no fee.`],
  ['booking-r', r => `Your booking is confirmed. The card was charged as expected and the confirmation is in your inbox.`],
  ['security-r', r => `Security notice: we have added extra protection to your account. You do not need to do anything.`],
  ['rx-r', r => `We tried to deliver your prescription but nobody was in. It is back at the pharmacy for collection, no charge.`],
  ['grandson-r', r => `It's your grandson — got the internship! Ring you tonight to tell you about it properly.`],
  ['landlord-r', r => `${pick(['Mum','Dad'],r)}, the landlord finally fixed the boiler! Hot water at last. Coming over Sunday if you're about.`],
  ['fr-colis-r', r => `Bonjour, votre colis a ete livre et depose chez le gardien. Bonne journee!`],
  ['bank-blocked-r', r => `This is your bank's security team confirming we've blocked the suspicious payment. Your card still works as normal.`],
  ['tickets-r', r => `I have two spare tickets for ${pick(['Saturday','the match'],r)} if anyone wants them — free to a good home, just let me know!`],
  ['recruit-r', r => `Congratulations on the role! HR will email the onboarding pack on Monday through the usual secure portal.`],
  ['grant-r', r => `Your property may qualify for the government green grant. Details are on the council website — no rush, the scheme runs all year.`],
  ['pendant-r', r => `Your relative asked us to let you know the medical alert pendant has arrived and is already paid for.`],
  ['viewing-r', r => `The ${pick(['flat','house'],r)} is still available. Viewings are Saturday between 10 and 2, just turn up, nothing to pay beforehand.`],
  ['water-r', r => `This is the water board. Works on your street start Monday and water may be off between 9 and 3. No access needed.`],
  ['simswap-r', r => `Alert: a SIM swap request was made on your number. If this wasn't you, ring us on the number on your statement.`],
  ['carehome-r', r => `Your ${pick(['father','mother'],r)}'s care home has sent this month's invoice to your email as usual. It's due at the end of the month.`],
  ['hospice-r', r => `Thank you for collecting for the children's hospice last year. The tin is ready whenever you can pop in.`],
  ['benefit-r', r => `You were overpaid benefits three years ago. It has already been written off, nothing is owed and no action is needed.`],
  ['trial-r', r => `Your free trial ends tonight and will convert to the paid plan. Cancel any time in the app if you'd rather not continue.`],
  ['bookkeep-r', r => `I'm the new bookkeeper — just introducing myself. Nothing needed from you, the payment run is unchanged.`],
  ['voicemail-r', r => `You have a voicemail from your ${pick(['son','daughter'],r)}. Listen in the app or ring your voicemail as usual.`],
  ['car-r', r => `The vehicle is exactly as described. Happy for you to come and view it, and pay however suits when you're satisfied.`],
  ['petins-r', r => `Your pet insurance renews next month at the same premium. The documents are in your account.`],
  ['roofer-r', r => `We're the roofing team who did next door. We've posted a card through if you ever want a free quote, no obligation.`],
  ['meter-r', r => `Your energy meter reading is due. Submit it in the app or reply with the numbers when convenient.`],
  ['es-cita', r => `Buenas tardes, su cita para la revision es el jueves a las diez. No hace falta hacer nada mas.`],
  // Officialdom doing ordinary, harmless things. Without these, "police",
  // "station", "officer" become scam words on their own — the front desk
  // returning a call about lost property was scoring 0.82.
  ['police-r2', r => `This is the police station front desk returning your call about the ${pick(['lost property','found bicycle','handbag'],r)}. It's here whenever you want it.`],
  ['police-r3', r => `PCSO ${pick(NAME,r)} here — thanks for reporting the ${pick(['broken fence','abandoned car'],r)}. It has been logged, nothing more needed from you.`],
  ['official-r', r => `The ${pick(['council','housing office','registrar'],r)} has received your form. Your reference is ${Math.floor(r()*900000+100000)} and we will write to you.`],
  ['lottery-r', r => `The lottery syndicate at work is up to 12 members. Same as always, no extra buy-in, I'll email the numbers.`],
  ['draw-r', r => `You've been entered into the members' prize draw. Free to enter, drawn on the ${Math.floor(r()*28+1)}, no purchase needed.`],
  ['darling-r', r => `My darling, the parcel arrived safely and it's beautiful. Thank you, I'll ring you at the weekend.`],
  // The hardest negative of all: a legitimate warning ABOUT scams. It is dense
  // with exactly the vocabulary that defines a scam — password, PIN, code,
  // "call", "never ask" — and a real bank warning was scoring 0.68, single-
  // handedly setting the threshold for the whole model.
  ['warn-r1', r => `${pick(BANK,r)}: we will never ask for your password or PIN. If you get such a call, hang up and ring the number on your card.`],
  ['warn-r2', r => `${pick(BANK,r)}: our staff will never ask you to move money to a safe account. If someone does, it is a scam.`],
  ['warn-r3', r => `Reminder: we will never send you a link to log in, and never ask for a one-time code. Report anything suspicious to us.`],
  ['warn-r4', r => `${pick(BRAND,r)}: beware of fake delivery texts asking for a fee. We will never request payment by text message.`],
  ['warn-r5', r => `Scam warning from your ${pick(['council','surgery','library'],r)}: callers are pretending to be us and asking for bank details. We never do this.`],
  ['warn-r6', r => `Action Fraud advice: never share a code, never move money because someone told you to, and always hang up and call back on a trusted number.`],
  ['warn-r7', r => `Your ${pick(['bank','building society'],r)} will never ask you to withdraw cash or hand your card to a courier. Please tell an older relative.`],
  ['police-r4', r => `This is the police station front desk returning your call about the lost property. It's here whenever you want it.`],
  ['officer-r', r => `PC ${pick(NAME,r)} here following up on the report you made. No further action needed, we'll write to you.`],
  ['app-r', r => `We've updated the banking app. Update it from the App Store as usual when you get a moment.`],
  ['neighbour-paid-r', r => `Our driver left your parcel with your neighbour at number ${Math.floor(r()*40+1)}. Nothing to pay, they've signed for it.`],
  ['job-r2', r => `Position confirmed. Training is provided on site and paid, starting Monday at 9. Bring photo ID.`],
  ['rebate-r', r => `Council tax rebate approved for your band. It will be credited to the account your direct debit comes from.`],
  ['clothing-r', r => `Thank you for the clothing donation last month. The shop raised over ${pick(['200','150'],r)} from your bags.`],
  ['syndicate-r', r => `The lottery syndicate at work is up to 12 members. Same as always, no extra buy-in, I'll email the numbers.`],
  ['timeshare-r', r => `Our legal team has completed the timeshare transfer. Everything is settled and there is nothing further to pay.`],
  ['council-r2', r => `The council has confirmed your liability was cleared last month. No further action and no agent will attend.`],
  ['pension-r3', r => `Your pension statement shows you can take benefits from 57. Speak to Pension Wise for free impartial guidance.`],
  ['darling-r2', r => `My darling, the parcel arrived safely and it's beautiful. Thank you, I'll ring you at the weekend.`],
  ['boss-r', r => `It's the boss — great work this week. Nothing needed from you, just wanted to say thanks before the weekend.`],
  ['school-paid-r', r => `School trip payment received, thank you. Your grandchild's place is confirmed and the kit list is attached.`],
  ['tariff-r', r => `Your energy tariff is ending. Compare options on the regulator's website or ring us on the number on your bill.`],
  ['permit-r', r => `Parking permit renewal is due. Renew online at the council website any time before the end of the month.`],
  ['supp-r', r => `Your supplement trial ends Friday and will not renew. If you'd like to continue, order any time from the shop.`],
  ['draw-r2', r => `You've been entered into the members' prize draw. Free to enter, drawn on the ${Math.floor(r()*28+1)}, no purchase needed.`],
  ['broadband-r', r => `Your broadband bill is due on the ${Math.floor(r()*28+1)} and will be taken by direct debit as usual.`],
  ['de-r3', r => `Ihre Bestellung wurde zugestellt und beim Nachbarn abgegeben. Vielen Dank!`],
  ['hmrc-r', r => `HMRC: you are due a tax refund of ${pick(['284.60','412.30'],r)}. It will be paid to your bank account automatically within 10 working days.`],
  ['landlord-r2', r => `I'm the landlord — happy to show you round Saturday. No money needed until the paperwork is signed.`],
  ['virus-r', r => `Your antivirus scan finished and found no problems. Next scan is scheduled for Sunday.`],
  ['admin-r', r => `Hi, I'm the new admin for the family group — just adding everyone's birthdays to the calendar, nothing needed from you.`],
  ['sponsor-r', r => `Sponsor me for the marathon! Here's my page on the charity's own fundraising site, every penny goes to them.`],
  ['rate-r', r => `Your savings account rate is changing to 4.1% from the 1st. No action needed, details in your online banking.`],
  ['ins-r', r => `Your insurance renewal quote is attached. Shop around if you like — you have until the 20th to decide.`],
  ['solar-r', r => `Your solar panels are due their optional five year check. It's up to you, and your warranty is unaffected.`],
  ['grant-r2', r => `The council is surveying homes for the insulation grant. Details and eligibility are on the council website.`],
  ['loan-r2', r => `Your loan application was approved. There are no upfront fees and the first repayment is on the 1st.`],
  ['acct-r2', r => `Your account was accessed from a new device. If this was you, no action is needed.`],
  ['licence-r4', r => `Your photo licence has been renewed for another 10 years. The certificate is in your account.`],
  ['nhs-r', r => `Your NHS appointment is confirmed for ${pick(['Tuesday','Friday'],r)} at 10:20. There is no charge, just bring your medication list.`],
  ['funeral-r', r => `Thanks for enquiring about funeral plans. The brochure is in the post, and there's no obligation at all.`],
  ['will-r', r => `Your will has been filed with us and remains valid. We'll write if the rules ever change.`],
  ['mortgage-r', r => `Your mortgage statement is ready. The balance and remaining term are in your online account.`],
  ['drains-r', r => `We were working on the drains next door — we've posted a card through in case you ever need us. No rush.`],
  ['refund-r3', r => `We refunded you twice by mistake. We've corrected it at our end, nothing needed from you.`],
  ['crypto-r', r => `The crypto exchange has completed your withdrawal. It should appear in your wallet shortly.`],
  ['fr-facture-r', r => `Votre facture de ce mois est disponible dans votre espace client. Prelevement le 5 comme d'habitude.`],
  ['charity-r2', r => `Donate to the ${pick(['Red Cross','local hospice','food bank'],r)} at their website or by calling their published number.`],
  ['dormant-r', r => `Your account has been inactive for a while. Nothing will happen to it, but do sign in if you'd like to keep it active.`],
  ['press-r', r => `Automated reminder: your ${pick(['car','boiler'],r)} is booked in for a service on ${pick(['Tuesday','Friday'],r)} at 9am.`],
  ['customs-ok', r => `Your package cleared customs with no charges and is scheduled for delivery ${pick(['tomorrow','Thursday'],r)}.`],
  ['customs-ok2', r => `Good news — the parcel is through customs, nothing to pay, and it's out with the driver today.`],
  ['phone-r', r => `New phone, same number — just so you have it saved. Nothing else, hope you're well!`],
  ['fall-r', r => `Hiya, it's ${pick(["next door's daughter","your neighbour"],r)}. Mum's had a fall but she's fine — just letting you know in case you heard the ambulance.`],
  ['school-ok', r => `Message from the school office: ${pick(['sports day','parents evening'],r)} bookings are now open on the portal.`],
  ['de-legit', r => `Guten Tag, Ihre Bestellung wurde versandt und kommt morgen an. Vielen Dank!`],
  ['de-legit2', r => `Ihr Termin ist am ${pick(['Dienstag','Donnerstag'],r)} um ${pick(['10:00','15:30'],r)} Uhr bestaetigt.`],
  // Systemic fix, not a one-off. Three times now a word that appeared ONLY in
  // scam templates became a scam signal on its own: "widower", Spanish, and now
  // "tax" (a property-tax receipt scored 0.78 while the next legitimate message
  // scored 0.36, and that single outlier set the threshold for everything).
  // Every institution and every frightening noun a scammer borrows must also
  // appear here, doing ordinary honest work.
  ['tax-r1', r => `${pick(['Property','Council','Vehicle'],r)} tax payment received. Receipt #${Math.floor(r()*9000+1000)}-${Math.floor(r()*9000+1000)}.`],
  ['tax-r2', r => `Your tax return was submitted successfully. Reference ${Math.floor(r()*900000+100000)}. Nothing further needed.`],
  ['tax-r3', r => `HMRC: your tax code has changed for the new year. Details are in your online account.`],
  ['police-r', r => `${pick(['Neighbourhood','Community'],r)} policing team: the drop-in surgery is at the library on ${pick(['Tuesday','Thursday'],r)} from 10am. No appointment needed.`],
  ['hospital-r', r => `Your ${pick(['scan','clinic','outpatient'],r)} appointment is confirmed for ${pick(['the 12th','Tuesday'],r)}. Please bring your list of medicines.`],
  ['bank-r5', r => `Your ${pick(BANK,r)} account was opened successfully. Your card and PIN will arrive separately.`],
  ['refund-r2', r => `Your refund of ${pick(AMT,r)} has been processed and will appear in 3 to 5 working days.`],
  ['warrant-r', r => `Your ${pick(['appliance','boiler','laptop'],r)} warranty covers this repair in full. Book a visit whenever suits you.`],
  ['secure-r', r => `We've upgraded security on your account. You don't need to do anything — just sign in as usual next time.`],
  ['urgent-r3', r => `Urgent: can anyone cover the ${pick(['stall','shift','collection'],r)} on Saturday? Let me know, thanks!`],
  ['verify-r', r => `Thanks for verifying your email address. Your account is all set up.`],
  ['invest-r', r => `Your ISA statement for the year is ready to view. Past performance is not a guide to future returns.`],
  ['complaint-r', r => `We got your complaint about the ${pick(['investment','account','service'],r)} charges and have escalated it. No fee for this, we'll update you within 10 days.`],
  ['complaint-r2', r => `Your case has been reviewed and the ${pick(['charge','fee'],r)} was refunded in full. Nothing further is needed from you.`],
  ['es-fam1', r => `Hola ${pick(['mama','papa','abuela'],r)}, llego ${pick(['10','15','20'],r)} minutos tarde a la cena. Nos vemos pronto!`],
  ['es-fam2', r => `Feliz cumpleanos ${pick(['abuelo','abuela','papa'],r)}! Que tengas un dia precioso. Un abrazo muy fuerte.`],
  ['es-fam3', r => `Puedes comprar pan y leche cuando vuelvas? Gracias!`],
  ['es-appt', r => `Su cita con el doctor ${pick(NAME,r)} es el ${pick(['martes','jueves'],r)} a las ${pick(['10:00','16:30'],r)}. Gracias.`],
  ['es-deliv', r => `Su pedido ha sido enviado y llegara ${pick(['manana','el jueves'],r)}. Puede seguirlo en la aplicacion.`],
  ['fr-fam1', r => `Salut ${pick(['maman','papa'],r)}, je serai en retard de ${pick(['10','20'],r)} minutes. A tout a l'heure!`],
  ['fr-fam2', r => `Joyeux anniversaire ${pick(['mamie','papi'],r)}! Passe une tres belle journee. Bisous.`],
  ['fr-deliv', r => `Votre commande a ete expediee et arrivera ${pick(['demain','jeudi'],r)}. Merci de votre confiance.`],
  ['fr-appt', r => `Votre rendez-vous est confirme pour ${pick(['mardi','vendredi'],r)} a ${pick(['9h','14h30'],r)}. A bientot.`],
  ['pt-fam1', r => `Oi ${pick(['mae','pai','vo'],r)}, vou chegar ${pick(['10','15'],r)} minutos atrasado. Ate ja!`],
  ['pt-deliv', r => `Seu pedido foi enviado e chegara ${pick(['amanha','na quinta'],r)}. Obrigado!`],
  ['es-legit', r => `Su cita con el doctor es el ${pick(['martes','jueves'],r)} a las ${pick(['10:00','16:30'],r)}. Gracias.`],
  ['fr-legit', r => `Votre commande a ete expediee et arrivera ${pick(['demain','jeudi'],r)}. Merci de votre confiance.`],
];

export function build(perTemplate = 26, seed = 7) {
  const r = rng(seed);
  const rows = [];
  for (const [id, fn] of SCAM) for (let i = 0; i < perTemplate; i++) rows.push({ text: fn(r), label: 1, tpl: 'S:' + id });
  for (const [id, fn] of LEGIT) for (let i = 0; i < perTemplate; i++) rows.push({ text: fn(r), label: 0, tpl: 'L:' + id });
  return rows;
}
export const TEMPLATE_COUNT = { scam: SCAM.length, legit: LEGIT.length };
