// DEV benchmark — tuned against. Novel messages, never in the training corpus.
// Repeated tuning against this set erodes its independence, which is exactly
// why scripts/bench/holdout.mjs exists and is read only at the end.
export const SCAM = [
  "Ms Chen from the Inland Revenue here. Our records show a discrepancy in your filing. I would advise you not to discuss it while the investigation is open.",
  "Nan!! Locked out of my accounts and mum's not picking up. Can you send something to tide me over till Friday?",
  "Your policy is set to auto-renew at a higher rate. To lock in the old price, confirm your card details on the portal before Friday.",
  "Hello, this is the technical department. We are seeing your router broadcasting on an insecure channel. I can fix it remotely if you let me on.",
  "Congratulations, your number was picked in our customer draw. To release the funds we just need the small transfer levy cleared first.",
  "I run a small crypto desk and my client list is closed, but a mutual friend spoke highly of you. Minimum entry is modest and returns are steady.",
  "Delivery attempted. Reschedule required. A handling amount of 1.79 is outstanding before we can release the item.",
  "This is a courtesy call regarding suspicious use of your national insurance number. Do not discuss this call with anyone until we verify you.",
  "Hi, sorry to bother — it's me from number 42. Had a bit of an emergency and I'm short. Could you help and I'll drop it back tomorrow?",
  "Your account will be closed for inactivity unless you log in through the secure portal today.",
  "We can help you claw back what you lost in that investment. Our success fee is only payable up front.",
  "Hola, soy del banco. Hemos detectado un cargo sospechoso. No cuelgue y confirme sus datos por favor.",
  "Good afternoon, I'm calling from the fraud prevention unit. Before we proceed can you confirm the long number on your card so I can verify you.",
  "Your grandson has been in an accident and needs representation. I am his solicitor. He asked me not to alarm his parents.",
  "Payment could not be processed for your recent order. Update your billing details within 12 hours or the order will be cancelled.",
  "We are conducting a routine audit of pension holdings. To confirm your entitlement please provide your policy and date of birth.",
  "You have been overcharged on your energy bill for 3 years. To process your refund we need your account and sort code.",
  "Hi love, it's me. Phone's playing up so using this one. Are you free? Bit of a situation and I didn't want to worry you.",
  "Our records indicate your warranty coverage has lapsed. Press one now to be connected with a coverage specialist.",
  "Your parcel is being held by customs. Import duty of 2.99 must be settled within 48 hours or the item will be returned.",
  "This is an automated message. Unusual activity was detected. Press 1 to speak with a security officer immediately.",
  "I saw your listing and I'd like to buy it. My courier will collect. I'll send extra to cover his fee, just forward that part on to him.",
  "URGENT: your child has been involved in an incident at school. Call this number immediately for details.",
  "Bonjour, votre compte sera bloque aujourd'hui. Confirmez vos informations sans tarder.",
  "Following the data breach we are issuing compensation. Confirm your identity and bank details to receive your payment.",
];
export const LEGIT = [
  "Ms Chen from the surgery here — your repeat prescription is ready whenever you want to pop in.",
  "Nan!! Just got my exam results and I passed everything!! Ringing you tonight xx",
  "Your policy auto-renews next month at the same rate. Nothing to do, but the documents are in your account.",
  "Hello, it's the engineer about your broadband appointment tomorrow — I should be with you between 9 and 11.",
  "Congratulations on the new job! We're all so pleased for you. Drinks on Friday to celebrate?",
  "I run a small pottery class on Tuesdays and there's a space free if you fancy it. No pressure!",
  "Delivery attempted today but nobody was home. We've left it in the porch as agreed. No charge.",
  "This is a courtesy call from the dentist about your check-up next Thursday. Ring us if that no longer suits.",
  "Hi, it's me from number 42 — took in a parcel for you, pop round any time this evening.",
  "Your account has been inactive for a while. If you'd like to keep it, just sign in through the app when convenient.",
  "We got your complaint about the investment charges and have escalated it. No fee for this, we'll update you within 10 days.",
  "Hola, soy Marta del club de lectura. La reunion es el jueves a las seis. Hasta pronto!",
  "Good afternoon, this is the bank calling about your appointment on Tuesday. Nothing urgent, just confirming the time.",
  "Your grandson called the house phone earlier — he's fine, just wanted a chat. Ring him back when you can.",
  "Payment received, thank you. Your order is being packed and will ship tomorrow.",
  "We're conducting our annual member survey. It takes 3 minutes and is completely optional.",
  "You've been overcharged on last month's bill. We've already credited your account, nothing for you to do.",
  "Hi love, it's me. Running late from work, don't wait for dinner. See you about eight x",
  "Our records show your warranty covers this repair in full. Book a visit whenever suits you.",
  "Your parcel cleared customs and is out for delivery today. No charges outstanding.",
  "This is an automated reminder that your library books are due back on Friday.",
  "I saw your listing and I'd like to buy it. Could I collect on Saturday morning and pay you then?",
  "Message from school: sports day is moved to Thursday due to the weather. No action needed.",
  "Bonjour, votre commande est prete a etre retiree en magasin. Merci beaucoup!",
  "Following the outage last week we've applied a credit to your account. It'll show on your next bill.",
];
