// FINAL validation set — written after all tuning was complete, and read once.
// dev.mjs and holdout.mjs were both used to fix bugs, so neither is an honest
// estimate any more. This one is. If it ever informs a change, it is spent too.
export const SCAM = [
  "Good morning, I'm calling from the pensions advisory service. There's an issue with your entitlement that we need to sort out before the deadline passes.",
  "Mum, the landlord's threatening to change the locks. I know it's a lot to ask but could you help me out until my wages land?",
  "Notification: your cloud storage is full and your photos will be deleted in 48 hours unless you upgrade using the secure form.",
  "Hello, we're calling about the accident you had that wasn't your fault. We can start your claim today, I just need a few details.",
  "You have been pre-approved for a loan of 5,000 at a fixed rate. To release the funds we require the arrangement fee up front.",
  "Sir, this is the anti-fraud bureau. Your identity has been used in a criminal matter. Remain on the line while I connect you to an officer.",
  "Your TV licence could not be renewed as the details we hold are out of date. Update them now to avoid a penalty.",
  "Hi! Sorry to message out of the blue. I got your number from the group. I've been trading forex and thought of you.",
  "The item is reserved for you but we need a deposit today to hold it, otherwise it goes to the next person on the list.",
  "This is a final notice from the debt recovery team regarding monies owed. Contact us today to avoid enforcement.",
  "Grandad, I'm so sorry, I've got myself into trouble and I can't tell mum and dad. Is there any way you could send me something?",
  "We are upgrading our systems. To keep your account active please re-register your card details through the link below.",
  "Hello, your computer's licence key has expired. Ring this number and a technician will renew it for you remotely.",
  "Attention: a payment of 749.00 to a foreign merchant is pending on your card. If you did not make this, call us on the number below.",
  "Bonjour, un colis vous attend. Des frais de livraison de 2,30 euros restent a regler avant expedition.",
  "I've been asked to contact you about compensation owed for mis-sold insurance. There is a small processing fee to release it.",
  "Your booking could not be confirmed as the card was declined. Re-enter your details within the hour or the room will be released.",
  "It's your grandson. I'm at the police station and they'll only release me if the fine is paid today. Please don't tell mum.",
  "Security alert: someone in another country is trying to access your account. Confirm your password to stop them.",
  "We tried to deliver your prescription but nobody was in. A small redelivery charge is payable before we can try again.",
];
export const LEGIT = [
  "Good morning, it's the pensions team — your annual statement has been posted and should reach you this week.",
  "Mum, the landlord finally fixed the boiler! Hot water at last. Coming over Sunday if you're about.",
  "Your cloud storage is nearly full. You can free up space or upgrade any time in settings — nothing will be deleted.",
  "Hello, we're calling to confirm your car is booked in for its service on Thursday. Nothing needed from you before then.",
  "You've been pre-approved for a higher limit. There's no charge and no obligation — details are in your online account.",
  "Sir, your order is ready for collection at the trade counter whenever suits you this week.",
  "Your TV licence renews automatically next month. The details we hold are up to date, so there's nothing to do.",
  "Hi! Sorry to message out of the blue — I got your number from the walking group. Are you going on Saturday?",
  "The item is reserved under your name until Friday. No deposit needed, just come in when you can.",
  "This is a reminder from the library that two books are overdue. No fine, just bring them back when you're passing.",
  "Grandad, I passed my exams!! Coming over at the weekend to tell you all about it. Love you.",
  "We're upgrading our systems on Sunday night. The app may be unavailable for a few hours — no action needed.",
  "Hello, your software licence renews automatically on the 14th. The receipt will be emailed to you.",
  "A payment of 749.00 to Wickes was authorised on your card ending 4417. View it in the app.",
  "Bonjour, votre colis a ete livre et depose chez le gardien. Bonne journee!",
  "We've reviewed your insurance complaint and upheld it. Your compensation will be paid automatically, with no fee.",
  "Your booking is confirmed. The card was charged as expected and the confirmation is in your inbox.",
  "It's your grandson — got the internship! Ring you tonight to tell you about it properly.",
  "Security notice: we've added extra protection to your account. You don't need to do anything.",
  "We tried to deliver your prescription but nobody was in. It's back at the pharmacy for collection, no charge.",
];
