// FOURTH validation set. Written after round 4, covering scam families that
// appear in NO rule and NO corpus template. Read once.
export const SCAM = [
  "This is your bank's security team. We're sending a courier to collect your card for safe destruction. Please cut it in half and hand it over.",
  "I have two tickets for Saturday going cheap as I can't make it. Bank transfer only I'm afraid, first come first served.",
  "Congratulations on the role! Before we finalise, please send a scan of your passport and your bank details for payroll.",
  "We noticed your property qualifies for a government green grant. The surveyor is in your area today and the discount ends tonight.",
  "Your relative has arranged a medical alert pendant for you. We just need to confirm the monthly payment details to activate it.",
  "The flat is still available. To secure the viewing slot please transfer the holding deposit today, plenty of interest on this one.",
  "This is the water board. We need access to check contamination in your area. Our operative will call round shortly.",
  "Alert: a SIM swap request was made on your number. If this wasn't you, reply STOP and confirm the last four digits of your account.",
  "Your father's care home fees are overdue and his place is at risk. Payment must be made today to avoid discharge.",
  "We're collecting for the local children's hospice. Card payment over the phone is easiest, or a bank transfer if you prefer.",
  "You were overpaid benefits three years ago. The sum must be repaid this week or it will be passed to enforcement.",
  "Free trial ends tonight. If you don't want to be charged 89.99 monthly, confirm your card so we can cancel it.",
  "I'm the new bookkeeper. The supplier bank details have changed, please use the new account for the invoice due today.",
  "Voice message from your son. He sounds distressed and mentions an accident. Press 1 to hear the full message.",
  "The vehicle is exactly as described. I'll hold it for you with a 500 deposit, my brother handles the paperwork.",
  "Your pet insurance lapsed last month. Reconfirm your card now or the policy cannot be reinstated.",
  "Following the death of your uncle abroad, you are named beneficiary. Legal costs must be cleared before funds transfer.",
  "We are the roofing team who did next door. We noticed slipped tiles on yours, we can sort it now for cash.",
  "Buenas tardes, somos del servicio tecnico. Su linea sera cortada hoy si no confirma sus datos bancarios.",
  "Your energy meter needs an urgent safety check. Confirm your account number and we'll book the engineer.",
];
export const LEGIT = [
  "This is your bank's security team confirming we've blocked the suspicious payment. Your card still works as normal.",
  "I have two spare tickets for Saturday if anyone wants them — free to a good home, just let me know!",
  "Congratulations on the role! HR will email the onboarding pack on Monday through the usual secure portal.",
  "Your property may qualify for the government green grant. Details are on the council website — no rush, the scheme runs all year.",
  "Your relative asked us to let you know the medical alert pendant has arrived and is already paid for.",
  "The flat is still available. Viewings are Saturday between 10 and 2, just turn up, nothing to pay beforehand.",
  "This is the water board. Works on your street start Monday and water may be off between 9 and 3. No access needed.",
  "Alert: a SIM swap request was made on your number. If this wasn't you, ring us on the number on your statement.",
  "Your father's care home has sent this month's invoice to your email as usual. It's due at the end of the month.",
  "Thank you for collecting for the children's hospice last year. The tin is ready whenever you can pop in.",
  "You were overpaid benefits three years ago. It has already been written off, nothing is owed and no action is needed.",
  "Your free trial ends tonight and will convert to the paid plan. Cancel any time in the app if you'd rather not continue.",
  "I'm the new bookkeeper — just introducing myself. Nothing needed from you, the payment run is unchanged.",
  "You have a voicemail from your son. Listen in the app or ring your voicemail as usual.",
  "The vehicle is exactly as described. Happy for you to come and view it, and pay however suits when you're satisfied.",
  "Your pet insurance renews next month at the same premium. The documents are in your account.",
  "Following your uncle's death, the solicitor will write to you directly. There is nothing to pay at this stage.",
  "We're the roofing team who did next door. We've posted a card through if you ever want a free quote, no obligation.",
  "Buenas tardes, su cita para la revision es el jueves a las diez. No hace falta hacer nada mas.",
  "Your energy meter reading is due. Submit it in the app or reply with the numbers when convenient.",
];
