// FIFTH validation set. Twenty scam families absent from every rule and every
// corpus template at the time of writing. Read once.
export const SCAM = [
  "Our legal team can release you from your timeshare obligations. The court application fee is payable before we can lodge it.",
  "Enforcement agent attending your address tomorrow regarding an unpaid liability. Settle now to prevent removal of goods.",
  "You can access your pension before 55 through a legitimate loophole. Transfer to our scheme and we handle the paperwork.",
  "My darling, I'm being held at customs over the gift I sent you. They want a clearance charge and my cards are frozen here.",
  "It's the boss. I'm in back-to-back meetings. Need you to buy gift cards for the client thank-yous and send me the codes.",
  "School trip payment failed. Please re-send via bank transfer today or your grandchild's place will be given away.",
  "You're paying too much for energy. I can switch you now over the phone, I just need your meter number and bank details.",
  "We collect clothing for the children's charity. Leave bags out Thursday, and any cash donations in the envelope provided.",
  "Our syndicate has won on 9 of the last 12 draws. A one-off buy-in secures your share of the next jackpot.",
  "Your banking app must be updated to meet new regulations. Install the update from the link to keep access.",
  "Unpaid parking charge notice. The amount doubles at midnight. Pay now to avoid court action.",
  "Your trial of the joint supplement is ending. We'll continue the monthly shipment at 79.99 unless you call to confirm cancellation.",
  "This is the police. Your card is being used by staff at your branch. Don't tell them — withdraw the cash and we'll collect it as evidence.",
  "Our driver couldn't reach you so your neighbour paid the customs charge. Please reimburse them via the link.",
  "You've been entered into the grand prize draw. A small entry confirmation fee applies before the draw closes.",
  "Position confirmed pending certification. The training module costs 149 and is refunded with your first pay packet.",
  "Council tax rebate approved for your band. Provide your account details and we'll process the refund today.",
  "As your appointed carer I'll need access to the account to manage the bills. It's simpler if you add me as a signatory.",
  "Ihr Paket konnte nicht zugestellt werden. Zahlen Sie die Gebuehr von 2,99 Euro ueber den Link.",
  "Your broadband will be disconnected within the hour for non-payment. Press 1 now to settle by card.",
];
export const LEGIT = [
  "Our legal team has completed the timeshare transfer. Everything is settled and there is nothing further to pay.",
  "The council has confirmed your liability was cleared last month. No further action and no agent will attend.",
  "Your pension statement shows you can take benefits from 57. Speak to Pension Wise for free impartial guidance.",
  "My darling, the parcel arrived safely and it's beautiful. Thank you, I'll ring you at the weekend.",
  "It's the boss — great work this week. Nothing needed from you, just wanted to say thanks before the weekend.",
  "School trip payment received, thank you. Your grandchild's place is confirmed and the kit list is attached.",
  "Your energy tariff is ending. Compare options on the regulator's website or ring us on the number on your bill.",
  "Thank you for the clothing donation last month. The shop raised over 200 from your bags.",
  "The lottery syndicate at work is up to 12 members. Same as always, no extra buy-in, I'll email the numbers.",
  "We've updated the banking app. Update it from the App Store as usual when you get a moment.",
  "Parking permit renewal is due. Renew online at the council website any time before the end of the month.",
  "Your supplement trial ends Friday and will not renew. If you'd like to continue, order any time from the shop.",
  "This is the police station front desk returning your call about the lost property. It's here whenever you want it.",
  "Our driver left your parcel with your neighbour at number 12. Nothing to pay, they've signed for it.",
  "You've been entered into the members' prize draw. Free to enter, drawn on the 30th, no purchase needed.",
  "Position confirmed. Training is provided on site and paid, starting Monday at 9. Bring photo ID.",
  "Council tax rebate approved for your band. It will be credited to the account your direct debit comes from.",
  "As your appointed carer I'll pop in Tuesday. The bills are all on direct debit so nothing needs doing.",
  "Ihre Bestellung wurde zugestellt und beim Nachbarn abgegeben. Vielen Dank!",
  "Your broadband bill is due on the 12th and will be taken by direct debit as usual.",
];
