// SIXTH validation set. Twenty more scam families absent from every rule and
// every corpus template at the time of writing. Read once.
export const SCAM = [
  "HMRC: you are due a tax refund of 284.60. Download our app and sign in to claim it before the deadline.",
  "I'm the landlord but I'm working abroad at the moment. Send the first month and I'll post the keys out to you.",
  "WARNING: your device is infected with 3 viruses. Do not restart. Call our certified technicians on the number shown.",
  "Hi, I'm the new admin for the family group. Verify your number by sending me the six digit code you'll receive.",
  "Sponsor me for the marathon! Just transfer to my personal account and I'll pass it all to the charity.",
  "Green energy bonds paying 8.4% fixed, capital protected, FSCS covered. Limited allocation remaining this quarter.",
  "We can beat your current insurance quote by 40%. I just need your policy number and card to secure the price today.",
  "Your solar panels are due their compulsory five year service. Failure to book invalidates your warranty.",
  "The council is surveying homes for the insulation grant. Confirm ownership and your date of birth and we'll book you in.",
  "Short term advance approved, no credit check. The security deposit is returned with your first repayment.",
  "Amazon: your account was accessed from a device in Lagos. If this wasn't you, verify your identity on the link now.",
  "Copyright infringement detected on your account. Pay the settlement fee within 72 hours or legal proceedings begin.",
  "Your NHS appointment requires a booking fee of 12.50 to be confirmed. Pay online to keep your slot.",
  "Have you considered a prepaid funeral plan? We can lock today's price if you set up the direct debit on this call.",
  "Your will is not legally valid under the new rules. Our specialist can rewrite it, the fee is payable up front.",
  "You could release 60,000 tax free from your home. No repayments ever. Reply YES for a callback from an adviser.",
  "We were working on the drains next door and noticed yours are collapsing. We can excavate today, cash price.",
  "Our error: we refunded you twice. Please return the duplicate 480 by bank transfer to the account below.",
  "Elon is doubling every coin sent to the giveaway address for the next hour. Send 0.1 and receive 0.2 back.",
  "Votre facture est impayee. Reglez sous 24 heures ou votre ligne sera suspendue.",
];
export const LEGIT = [
  "HMRC: you are due a tax refund of 284.60. It will be paid to your bank account automatically within 10 working days.",
  "I'm the landlord — happy to show you round Saturday. No money needed until the paperwork is signed.",
  "Your antivirus scan finished and found no problems. Next scan is scheduled for Sunday.",
  "Hi, I'm the new admin for the family group — just adding everyone's birthdays to the calendar, nothing needed from you.",
  "Sponsor me for the marathon! Here's my page on the charity's own fundraising site, every penny goes to them.",
  "Your savings account rate is changing to 4.1% from the 1st. No action needed, details in your online banking.",
  "Your insurance renewal quote is attached. Shop around if you like — you have until the 20th to decide.",
  "Your solar panels are due their optional five year check. It's up to you, and your warranty is unaffected.",
  "The council is surveying homes for the insulation grant. Details and eligibility are on the council website.",
  "Your loan application was approved. There are no upfront fees and the first repayment is on the 1st.",
  "Amazon: your account was accessed from a new device. If this was you, no action is needed.",
  "Your photo licence has been renewed for another 10 years. The certificate is in your account.",
  "Your NHS appointment is confirmed for Tuesday at 10:20. There is no charge, just bring your medication list.",
  "Thanks for enquiring about funeral plans. The brochure is in the post, and there's no obligation at all.",
  "Your will has been filed with us and remains valid. We'll write if the rules ever change.",
  "Your mortgage statement is ready. The balance and remaining term are in your online account.",
  "We were working on the drains next door — we've posted a card through in case you ever need us. No rush.",
  "We refunded you twice by mistake. We've corrected it at our end, nothing needed from you.",
  "The crypto exchange has completed your withdrawal. It should appear in your wallet shortly.",
  "Votre facture de ce mois est disponible dans votre espace client. Prelevement le 5 comme d'habitude.",
];
