// HOLDOUT benchmark — read ONCE, at the very end, to get an honest number.
// Not used for tuning, not consulted between rounds. If it is ever used to pick
// a threshold or a rule, it stops being a holdout and this comment is a lie.
export const SCAM = [
  "Afternoon. I'm from the council tax office. Our system shows an underpayment going back two years and I need to resolve it with you today.",
  "Grandad it's Jamie. I've had a bump in the car and the other driver wants cash to not report it. Please don't say anything to dad.",
  "Your streaming plan could not be renewed. Re-enter your payment information to avoid losing your watchlist.",
  "This is the helpdesk. We've had an alert from your machine. If you can get to a computer I'll walk you through securing it.",
  "You have an unclaimed rebate of 340 from the energy price cap. Verify your details to have it paid into your account.",
  "A friend mentioned you might be interested. I've been putting money into a managed fund and the monthly returns have been consistent.",
  "Item held at depot. Small fee outstanding for storage before release can be arranged.",
  "We're ringing about irregular activity on your utility account. Please don't end the call while I transfer you to the fraud team.",
  "Hiya, it's next door's daughter. Mum's had a fall and I've had to rush out without my purse. Any chance you could help?",
  "Dormant account notice: sign in via the link provided to prevent permanent closure of your savings.",
  "Our firm specialises in recovering funds lost to fraudulent schemes. An initial administration charge applies.",
  "Buenos dias, hay un problema con su cuenta. Necesitamos que confirme su numero de tarjeta ahora mismo.",
  "Calling from the card protection team — to confirm I'm talking to the right person, could you read me the three digits on the back?",
  "I represent your nephew in a legal matter. He's asked that his mother not be told while bail is arranged.",
  "Order on hold. Confirm your card within 6 hours or we will release the item to another customer.",
  "Pension review: to confirm your entitlement we need your policy number and national insurance number.",
  "Our audit found you were charged incorrectly. To return the money we'll need your account number and sort code.",
  "It's me darling, different phone, mine's in for repair. Are you around? Something's come up and I can't ring.",
  "Your cover is about to end. Press two now to be transferred to a renewals advisor before your policy lapses.",
  "Package detained pending duty payment of 3.49. Settle within 24 hours to avoid it being returned to sender.",
  "Automated security notice. Irregular sign-in detected. Press 1 immediately to lock your account.",
  "I'd like to purchase the item. My shipping agent will collect — I'll add his fee to the payment, please pass it to him on arrival.",
  "This is the school office. There has been an incident involving your grandchild. Please ring back on this number urgently.",
  "Guten Tag, Ihr Konto wird heute gesperrt. Bitte bestatigen Sie sofort Ihre Daten.",
  "As a result of the recent breach you are entitled to compensation. Confirm your identity and bank details to proceed.",
];
export const LEGIT = [
  "Afternoon — it's the council about your garden waste collection. It moves to Wednesdays from next month.",
  "Grandad it's Jamie. Passed my driving test first time!! Coming round Sunday to show you the car.",
  "Your streaming plan renews on the 8th at the usual price. Manage it any time in settings.",
  "This is the helpdesk following up on the ticket you raised. It's resolved — no action needed at your end.",
  "You're due a rebate of 340 from the energy price cap. It'll be credited automatically next month.",
  "A friend mentioned you might be interested — we've got a spare seat in the walking group on Saturdays.",
  "Item is at the depot ready for collection. Open until 5, no fee.",
  "We're ringing about the direct debit you set up. It's all gone through fine, just confirming for your records.",
  "Hiya, it's next door's daughter. Mum's had a fall but she's OK — just letting you know in case you heard the ambulance.",
  "Your account has been dormant a while. Nothing will happen to it, but do sign in if you'd like to keep it active.",
  "Our firm has completed the conveyancing. The final statement is enclosed and there's nothing further to pay.",
  "Buenos dias, su pedido esta listo para recoger en la tienda. Muchas gracias!",
  "Calling from the card team — your replacement card was posted yesterday and should arrive Thursday.",
  "I represent the estate and can confirm probate has completed. No action needed from you at this stage.",
  "Order confirmed. We'll email tracking as soon as it leaves the warehouse.",
  "Pension statement: your annual summary is now available to view in your online account.",
  "Our audit found you were charged incorrectly last year. A refund has been issued to your original payment method.",
  "It's me darling — got the tickets for Saturday. Shall I pick you up at six?",
  "Your cover renews automatically on the 30th at the same premium. Documents are in your account.",
  "Package cleared customs with no charges and is scheduled for delivery tomorrow.",
  "Automated reminder: your car is booked in for a service on Tuesday at 9am.",
  "I'd like to purchase the item if it's still available. Happy to collect and pay cash on the day.",
  "Message from the school office: parents evening bookings are now open on the portal.",
  "Guten Tag, Ihre Bestellung wurde versandt und kommt morgen an. Vielen Dank!",
  "Following the outage we've credited your account automatically. It'll appear on your next statement.",
];
